OPENAI_API_KEY = "Your_OPENAI_API_KEY_HERE"
GOOGLE_GEMINI_API_KEY = "YOUR_GOOGLE_GEMINI_API_KEY_HERE"
DEEPSEEK_API_KEY = "YOUR_DEEPSEEK_API_KEY_HERE"
HUGGINGFACE_ENDPOINT_LLAMA = "YOUR_HUGGINGFACE_ENDPOINT_LLAMA_HERE"
HUGGINGFACE_API_KEY = "YOUR_HUGGINGFACE_API_KEY_HERE"


